#!/bin/bash
# PRUVIQ — Daily Market Report Generator
# Uses Ollama qwen2.5:32b to generate a daily market report.
#
# Crontab: 0 6 * * * /Users/jepo/pruviq/backend/scripts/daily_report.sh
# Output: ~/pruviq-reports/YYYY-MM-DD.md (for human review)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
ENV_FILE="$REPO_DIR/backend/.env"
REPORT_DIR="$HOME/pruviq-reports"
TODAY=$(date -u +%Y-%m-%d)
LOG_FILE="$HOME/pruviq-pipeline.log"

mkdir -p "$REPORT_DIR"

if [ -f "$ENV_FILE" ]; then
    set -a
    source "$ENV_FILE"
    set +a
fi

log() { echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC') — $*" | tee -a "$LOG_FILE"; }

notify() {
    if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="$1" \
            -d parse_mode="Markdown" > /dev/null 2>&1 || true
    fi
}

# Helper: parse JSON field with python
parse_json() {
    local field="$1"
    local fmt="${2:-s}"
    python3 -c "
import json, sys
d = json.load(sys.stdin)
v = d.get('$field', None)
if v is None:
    print('N/A')
elif '$fmt' == 'price':
    print(f'{float(v):,.0f}')
elif '$fmt' == 'pct':
    print(f'{float(v):+.2f}%')
else:
    print(v)
" 2>/dev/null || echo "N/A"
}

log "=== Daily Report Start ==="

# Step 1: Collect market data
log "Collecting market data..."
BTC_DATA=$(curl -s "https://api.binance.com/api/v3/ticker/24hr?symbol=BTCUSDT" 2>/dev/null || echo '{}')
BTC_PRICE=$(echo "$BTC_DATA" | parse_json "lastPrice" "price")
BTC_CHANGE=$(echo "$BTC_DATA" | parse_json "priceChangePercent" "pct")

ETH_DATA=$(curl -s "https://api.binance.com/api/v3/ticker/24hr?symbol=ETHUSDT" 2>/dev/null || echo '{}')
ETH_PRICE=$(echo "$ETH_DATA" | parse_json "lastPrice" "price")
ETH_CHANGE=$(echo "$ETH_DATA" | parse_json "priceChangePercent" "pct")

# PRUVIQ simulation stats
SIM_DATA=$(curl -s -X POST http://localhost:8080/simulate \
    -H 'Content-Type: application/json' \
    -d '{"strategy":"bb-squeeze","direction":"short","sl_pct":10,"tp_pct":8,"top_n":50}' 2>/dev/null || echo '{}')
SIM_WR=$(echo "$SIM_DATA" | parse_json "win_rate")
SIM_PF=$(echo "$SIM_DATA" | parse_json "profit_factor")

# Fear & Greed
FG_DATA=$(curl -s "https://api.alternative.me/fng/" 2>/dev/null || echo '{"data":[{"value":"N/A","value_classification":"N/A"}]}')
FG_VALUE=$(echo "$FG_DATA" | python3 -c 'import json,sys; print(json.load(sys.stdin)["data"][0]["value"])' 2>/dev/null || echo "N/A")
FG_CLASS=$(echo "$FG_DATA" | python3 -c 'import json,sys; print(json.load(sys.stdin)["data"][0]["value_classification"])' 2>/dev/null || echo "N/A")

log "BTC: \$$BTC_PRICE ($BTC_CHANGE), ETH: \$$ETH_PRICE ($ETH_CHANGE), F&G: $FG_VALUE"

# Step 2: Generate report with Ollama
log "Generating report with Ollama..."

PROMPT="You are writing a concise daily crypto market report for the PRUVIQ blog.

Today's data ($TODAY):
- BTC: \$$BTC_PRICE ($BTC_CHANGE 24h)
- ETH: \$$ETH_PRICE ($ETH_CHANGE 24h)
- Fear & Greed Index: $FG_VALUE ($FG_CLASS)
- BB Squeeze SHORT simulation: WR=$SIM_WR%, PF=$SIM_PF

Write a brief market report (200-300 words) in markdown:
1. Market Summary (2-3 sentences about BTC/ETH trend)
2. Sentiment ($FG_CLASS context)
3. Strategy Note (what this means for short sellers)

Rules:
- Use ONLY the data provided above. Do NOT invent prices or statistics.
- No price predictions or financial advice.
- End with: *Disclaimer: This is not financial advice. Past performance does not guarantee future results.*
- Tone: analytical, factual, concise."

# Escape for JSON using Python
PROMPT_ESCAPED=$(echo "$PROMPT" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')

RESPONSE=$(curl -s -m 120 http://localhost:11434/api/generate \
    -d "{\"model\":\"qwen2.5:32b\",\"prompt\":$PROMPT_ESCAPED,\"stream\":false}" 2>/dev/null || echo '{"response":"Generation failed"}')

REPORT=$(echo "$RESPONSE" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("response","Generation failed"))' 2>/dev/null || echo "Generation failed")

if [ "$REPORT" = "Generation failed" ]; then
    log "FAILED: Ollama generation failed"
    notify "⚠️ *PRUVIQ Daily Report*: Generation failed"
    exit 1
fi

# Step 3: Save report
REPORT_FILE="$REPORT_DIR/$TODAY.md"
python3 -c "
import sys
report = sys.argv[1]
today = sys.argv[2]
btc_p = sys.argv[3]
btc_c = sys.argv[4]
fg_v = sys.argv[5]
fg_c = sys.argv[6]

with open(sys.argv[7], 'w') as f:
    f.write(f'''---
title: \"Daily Market Report — {today}\"
date: {today}
btc_price: {btc_p}
btc_change: {btc_c}
fear_greed: {fg_v} ({fg_c})
status: draft
---

{report}

---

*Data sources: Binance API, Alternative.me Fear & Greed Index, PRUVIQ Simulation Engine*
*Generated by Ollama qwen2.5:32b — requires human review before publishing*
''')
" "$REPORT" "$TODAY" "$BTC_PRICE" "$BTC_CHANGE" "$FG_VALUE" "$FG_CLASS" "$REPORT_FILE"

log "Report saved: $REPORT_FILE"

# Step 4: Notify for review
notify "📝 *Daily Report Ready* ($TODAY)
BTC: \$$BTC_PRICE ($BTC_CHANGE)
F&G: $FG_VALUE ($FG_CLASS)
Report saved for review."

log "=== Daily Report Complete ==="
