#!/usr/bin/env python3
"""
Generate src/data/coin-symbols.ts from CSV data files.

Reads data/futures/*.csv, filters by minimum rows and blacklist,
and outputs a TypeScript module with the COIN_SYMBOLS array.
"""

import os
from pathlib import Path

# Paths
DATA_DIR = Path(os.getenv(
    "PRUVIQ_DATA_DIR",
    str(Path(__file__).parent.parent.parent.parent / "autotrader" / "data" / "futures")
))
OUTPUT = Path(__file__).parent.parent.parent / "src" / "data" / "coin-symbols.ts"

MIN_ROWS = 500
SKIP = {"intcusdt", "tslausdt", "hoodusdt", "paxgusdt", "gunusdt"}


def main():
    files = sorted(DATA_DIR.glob("*_1h.csv"))
    symbols = []

    for f in files:
        stem = f.stem.replace("_1h", "")
        if stem in SKIP:
            continue

        # Count lines (header + data)
        with open(f) as fh:
            line_count = sum(1 for _ in fh)

        if line_count - 1 < MIN_ROWS:
            continue

        symbols.append(stem.upper())

    symbols.sort()

    # Write TypeScript
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, "w") as out:
        out.write("// Auto-generated by backend/scripts/generate_coin_symbols.py\n")
        out.write("// Do not edit manually.\n\n")
        out.write("export const COIN_SYMBOLS = [\n")
        for i, sym in enumerate(symbols):
            comma = "," if i < len(symbols) - 1 else ""
            out.write(f"  '{sym}'{comma}\n")
        out.write("] as const;\n\n")
        out.write(f"export type CoinSymbol = typeof COIN_SYMBOLS[number];\n")

    print(f"Generated {OUTPUT} with {len(symbols)} symbols")


if __name__ == "__main__":
    main()
