#!/bin/bash
# PRUVIQ Performance Data Auto-Update Pipeline
#
# 전체 흐름:
#   1. AutoTrader 서버에서 최신 trades JSON 백업
#   2. generate_performance_data.py 실행 → performance.json 생성
#   3. 변경사항 있으면 git commit + push → Cloudflare Pages 자동 배포
#
# crontab (매일 03:00 UTC):
#   0 3 * * * /Users/jplee/Desktop/pruviq/backend/scripts/update_performance_and_push.sh >> ~/pruviq-perf-update.log 2>&1

set -euo pipefail

PRUVIQ_DIR="/Users/jplee/Desktop/pruviq"
AUTOTRADER_DIR="/Users/jplee/Desktop/autotrader"
PERFORMANCE_JSON="${PRUVIQ_DIR}/public/data/performance.json"
BACKUP_SCRIPT="${AUTOTRADER_DIR}/scripts/backup_server_data.sh"
GENERATE_SCRIPT="${PRUVIQ_DIR}/backend/scripts/generate_performance_data.py"
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

log() {
    echo "[${TIMESTAMP}] $1"
}

log "=== PRUVIQ Performance Update Start ==="

# Step 1: Backup latest trades from server
log "Step 1/3: Backing up trades from server..."
if [[ -x "${BACKUP_SCRIPT}" ]]; then
    "${BACKUP_SCRIPT}" 2>&1 || {
        log "WARNING: Backup script failed, continuing with existing data"
    }
else
    log "WARNING: Backup script not found or not executable: ${BACKUP_SCRIPT}"
fi

# Step 2: Generate performance.json
log "Step 2/3: Generating performance.json..."
PYTHON_CMD="python3"
if ! command -v python3 &>/dev/null; then
    PYTHON_CMD="python"
fi

${PYTHON_CMD} "${GENERATE_SCRIPT}" 2>&1 || {
    log "ERROR: generate_performance_data.py failed"
    exit 1
}

# Check output exists
if [[ ! -f "${PERFORMANCE_JSON}" ]]; then
    log "ERROR: performance.json not generated"
    exit 1
fi

# Step 3: Git commit + push (only if changed)
log "Step 3/3: Checking for changes..."
cd "${PRUVIQ_DIR}"

# Check if performance.json has actual changes
if git diff --quiet -- "public/data/performance.json" 2>/dev/null; then
    log "No changes in performance.json, skipping commit"
    log "=== Done (no update needed) ==="
    exit 0
fi

# Stage and commit
git add "public/data/performance.json"

PERF_DATE=$(${PYTHON_CMD} -c "import json; d=json.load(open('${PERFORMANCE_JSON}')); print(d['period']['to'])" 2>/dev/null || echo "unknown")
TRADES=$(${PYTHON_CMD} -c "import json; d=json.load(open('${PERFORMANCE_JSON}')); print(d['summary']['total_trades'])" 2>/dev/null || echo "?")

git commit -m "$(cat <<EOF
chore: update performance data (${PERF_DATE}, ${TRADES} trades)

Auto-generated by update_performance_and_push.sh
EOF
)"

# Push to trigger Cloudflare Pages deployment
git push origin main 2>&1 || {
    log "ERROR: git push failed"
    exit 1
}

log "Pushed to GitHub → Cloudflare Pages will auto-deploy"
log "=== Done ==="
